const GET_TASKS = 'TASKS/GET_TASKS'
const GET_TASKS_SUCCESS = 'TASKS/GET_TASKS SUCCESS'
const GET_TASKS_FAILURE = 'TASKS/GET_TASKS FAILURE'
const POST_TASK = 'TASKS/POST TASK'
const POST_TASK_SUCCESS = 'TASKS/POST TASK SUCCESS'
const POST_TASK_FAILURE = 'TASKS/POST TASK FAILURE'

export {
  GET_TASKS,
  GET_TASKS_SUCCESS,
  GET_TASKS_FAILURE,
  POST_TASK,
  POST_TASK_SUCCESS,
  POST_TASK_FAILURE
}
