const GET_TASKS = 'TASKS/GET_TASKS'
const GET_TASKS_SUCCESS = 'TASKS/GET_TASKS SUCCESS'
const GET_TASKS_FAILURE = 'TASKS/GET_TASKS FAILURE'
const POST_TASK = 'TASKS/POST TASK'
const POST_TASK_SUCCESS = 'TASKS/POST TASK SUCCESS'
const POST_TASK_FAILURE = 'TASKS/POST TASK FAILURE'
const DELETE_TASK = 'TASKS/DELETE TASK'
const DELETE_TASK_SUCCESS = 'TASKS/DELETE TASK SUCCESS'
const DELETE_TASK_FAILURE = 'TASKS/DELETE TASK FAILURE'
const CHECKED_TASK = 'TASKS/CHECKED TASK'
const CHECKED_TASK_SUCCESS = 'TASKS/CHECKED TASK SUCCESS'
const CHECKED_TASK_FAILURE = 'TASKS/CHECKED TASK FAILURE'

export {
  GET_TASKS,
  GET_TASKS_SUCCESS,
  GET_TASKS_FAILURE,
  POST_TASK,
  POST_TASK_SUCCESS,
  POST_TASK_FAILURE,
  DELETE_TASK,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAILURE,
  CHECKED_TASK,
  CHECKED_TASK_SUCCESS,
  CHECKED_TASK_FAILURE
}
