const GET_TASKS = 'TASKS/GET_TASKS'
const GET_TASKS_SUCCESS = 'TASKS/GET_TASKS SUCCESS'
const GET_TASKS_FAILURE = 'TASKS/GET_TASKS FAILURE'

export { GET_TASKS, GET_TASKS_SUCCESS, GET_TASKS_FAILURE }
